Project1.WebApp/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Project1.DataAccess.Repositories;
using Project1.DataAccess.Model;
using Project1.Library.Entities;
using Project1.WebApp.ViewModels;

namespace Project1.WebApp.Controllers
{
    public class CustomerController : Controller
    {
        public CustomerRepository Repo { get;}

        public CustomerController(CustomerRepository repo) =>
            Repo = repo ?? throw new ArgumentNullException(nameof(repo));

        // GET: CustomerController
        public ActionResult Index([FromQuery]string search = "")
        {
            IEnumerable<CustomerEntity> customers = (IEnumerable<CustomerEntity>)Repo.GetAll(search);
            IEnumerable<CustomerViewModel> viewModels = customers.Select(x => new CustomerViewModel
            {
                Id = x.CustomerId,
                FirstName = x.FirstName,
                LastName = x.LastName,
                UserName = x.UserName
            });
            return View(viewModels);
        }

        // GET: CustomerController/Details/5
        public ActionResult Details(int id)
        {
            CustomerEntity customer = Repo.GetById(id);
            var viewModel = new CustomerViewModel
            {
                Id = customer.CustomerId,
                FirstName = customer.FirstName,
                LastName = customer.LastName,
                UserName = customer.UserName
            };
            return View(viewModel);
        }

        // GET: CustomerController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CustomerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("FirstName", "LastName", "UserName")]CustomerViewModel viewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string FirstName, LastName, UserName;
                    CustomerEntity customer = new CustomerEntity
                    (
                        FirstName = viewModel.FirstName,
                        LastName = viewModel.LastName,
                        UserName = viewModel.UserName
                    ) ;
                        
                    Repo.Insert(customer);
                    Repo.Save();

                    return RedirectToAction(nameof(Index));
                }
                return View(viewModel);
            }
            catch
            {
                return View(viewModel);
            }
        }

        // GET: CustomerController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CustomerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CustomerController/Delete/5
        public ActionResult Delete(int id)
        {
            //get cust by id
            CustomerEntity customer = Repo.GetById(id);
            var viewModel = new CustomerViewModel
            {
                Id = customer.CustomerId,
                FirstName = customer.FirstName,
                LastName = customer.LastName,
                UserName = customer.UserName
            };

            return View(viewModel);
        }

        // POST: CustomerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, [BindNever]IFormCollection collection)
        {
            try
            {
                Repo.Delete(id);
                Repo.Save();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Project1.WebApp/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Project1.DataAccess.Repositories;
using Project1.Library.Entities;
using Project1.WebApp.ViewModels;

namespace Project1.WebApp.Controllers
{
    public class OrderController : Controller
    {
        public OrderRepository Repo { get; }

        public OrderController(OrderRepository repo) =>
            Repo = repo ?? throw new ArgumentNullException(nameof(repo));

        // GET: OrderController
        public ActionResult Index()
        {
            return View();
        }

        // GET: OrderController/Create
        public ActionResult Create()//Place new order
        {
            return View();
        }

        public ActionResult ListOrders()
        {
            IEnumerable<OrderEntity> custOrders = Repo.GetOrders();
            IEnumerable<OrderViewModel> viewModels = custOrders.Select(x => new OrderViewModel
            {
                OrderId = x.OrderId,
                OrderDate = x.OrderDate
            });
            return View(viewModels);
        }

        public ActionResult SelectProducts(int StoreId, int CustomerId)
        {
            if (ModelState.IsValid)
            {
                var viewModel = new OrderViewModel { StoreId = StoreId, CustomerId = CustomerId };
                return View(viewModel);
            }
            else
            {
                return RedirectToAction(nameof(Create));
            }
        }

        // POST: OrderController/Create
        public ActionResult Checkout(int StoreId, int CustId, int prodID, int prodQty)
        {
            try
            {
                //Validate data entered.
                

                OrderEntity order = new OrderEntity
                {
                    OrderDate = DateTime.Now,
                    StoreId = StoreId,
                    CustomerId = CustId
                };

                Repo.InsertOrder(order, prodID, prodQty);

                return RedirectToAction(nameof(Create));
            }
            catch (Exception)
            {
                return RedirectToAction(nameof(Index));
            }
        }

        public ActionResult CustDetails(int id)
        {
            OrderEntity order = (OrderEntity)Repo.GetCustomerHistoryById(id);
            var viewModel = new OrderViewModel
            {
                OrderId = order.OrderId,
                OrderDate = order.OrderDate,
                StoreId = order.StoreId,
                CustomerId = order.CustomerId,
                Orders = order.Orders
            };
            return View(viewModel);
        }

        public ActionResult StoreDetails(int id)
        {
            OrderEntity order = (OrderEntity)Repo.GetStoreHistoryById(id);
            var viewModel = new OrderViewModel
            {
                OrderId = order.OrderId,
                OrderDate = order.OrderDate,
                StoreId = order.StoreId,
                CustomerId = order.CustomerId,
                Orders = order.Orders
            };
            return View(viewModel);
        }

        //GET: OrderController/DisplayCustOrders
        public ActionResult DisplayCustOrders()
        {
            IEnumerable<OrderEntity> custOrders = Repo.GetAll();
            IEnumerable<OrderViewModel> viewModels = custOrders.Select(x => new OrderViewModel
            {
                OrderId = x.OrderId,
                OrderDate = x.OrderDate,
                StoreId = x.StoreId,
                CustomerId = x.CustomerId
            });
            return View(viewModels);
        }
        //GET: OrderController/DisplayStoreOrders
        public ActionResult DisplayStoreOrders()
        {
            IEnumerable<OrderEntity> storeOrders = Repo.GetAll();
            IEnumerable<OrderViewModel> viewModels = storeOrders.Select(x => new OrderViewModel
            {
                OrderId = x.OrderId,
                OrderDate = x.OrderDate,
                StoreId = x.StoreId,
                CustomerId = x.CustomerId
            });
            return View(viewModels);
        }
    }
}

Project1.WebApp/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Project1.DataAccess.Repositories;
using Project1.Library.Entities;
using Project1.WebApp.ViewModels;

namespace Project1.WebApp.Controllers
{
    public class StoreController : Controller
    {
        public StoreRepository Repo { get; }

        public StoreController(StoreRepository repo) =>
            Repo = repo ?? throw new ArgumentNullException(nameof(repo));


        // GET: StoreController
        public ActionResult Index([FromQuery] string search = "")
        {
            IEnumerable<StoreEntity> stores = (IEnumerable<StoreEntity>)Repo.GetAll(search);
            IEnumerable<StoreViewModel> viewModels = stores.Select(x => new StoreViewModel
            {
                Id = x.StoreId,
                StoreName = x.StoreName,
                StoreAddress = x.StoreAddress
            });
            return View(viewModels);
        }

        // GET: StoreController/Details/5
        public ActionResult Details(int id)
        {
            StoreEntity store = Repo.GetById(id);
            var viewModel = new StoreViewModel
            {
                Id = store.StoreId,
                StoreName = store.StoreName,
                StoreAddress = store.StoreAddress,
                Inventory = store.StoreInventory
                
            };
            return View(viewModel);
        }
    }
}

Project1.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" id="custom-nav">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="">Stores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="">Orders</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - @ViewData["Title"] - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>